### PR TITLE
- Additional options added for iOS,  Fix share issue with SDK version 24 or above on Android

### PR DESCRIPTION
**Pull request by almas**
- Additional options added for iOS
- Made iOS no share button view same as Android (like fullscreen)
- Fix share crash issue with SDK version 24 or above on Android
- Changed argument json passing to simple array because of iOS json problems

### CODE REVIEW

**Comment by writer0713** [comment]
plz merge this request. I need this fix!

**Comment by writer0713** [comment]
@almas thanks man. I found that same issue has reported in the past many times, but has not fixed yet. Hope your request would be merged into master branch :)

**Comment by mirko77** [comment]
Need this as well

**Comment by almas** [comment]
Hi guys

You can install it and using from my fork like this

```
cordova plugin remove com-sarriaroman-photoviewer
cordova plugin add https://github.com/almas/photoviewer.git

```
Or maybe replace cordova with ionic should also work. If there is an error with npm git problem then you might downgrade your npm version to 3.10.10 or you can do this like below with manual download.

```
cd /tmp
git clone https://github.com/almas/photoviewer.git
cordova plugin add /tmp/photoviewer
```

**Comment by writer0713** [comment]
@almas Thanks for your reply. However, I'm waiting for merging into master branch. If I change the command once, it will affect package.json. Thanks!

**Comment by sarriaroman** [comment]
Thanks for the awesome changes, I've been testing the changes and I will merge them (as soon as github let me do it, It's not working right now for some reason)

**Comment by sarriaroman** [comment]
Published to NPM. Thanks all :)

**Comment by writer0713** [comment]
@sarriaroman @almas thank you all guys. I'll update to this new version tomorrow :)

**Comment by nginx17** [comment]
@sarriaroman thank you

**Comment by writer0713** [comment]
@sarriaroman @almas - hi, I've used the new version library. and there's an error on ios when I pass 'options'. 

(with no options, it works well)

error : 
```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIDocumentInteractionController: invalid scheme http.  Only the file scheme is supported.'
```

Any solutions?

**Pull request merged**
