### PR TITLE
fixed issue of hiding loader on image load for android

### PR DESCRIPTION
**Pull request by techmanha**
If we load PNG image the loader is visible in background

### CODE REVIEW

**Comment by sarriaroman** [comment]
Can you please fix the conflicts? I will merge it! Thanks for your contribution!

**Comment by Manduro** [comment]
This is already fixed on latest master

**Comment by sarriaroman** [comment]
Yes, I checked the code just in case and saw the solution. Thanks for the great contributions!!! :D

**Comment by rakeshbaral92** [comment]
Thanks for this beautiful answer. Worked like a charm.

**Pull request closed without merging**
